server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: eureka-client-ex
          uri: lb://eureka-client-ex
          predicates:
            - Path=/test/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
